spring.application.name=UserList

spring.datasource.url=jdbc:mysql://localhost:3306/
spring.datasource.usename=D2_87273_Suraj
sping.datasource.password=manager

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
